### ISSUE TITLE
Unable to specify stacks that don't have `app-` prefix

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk-docker#173]
E.g. govuk-content-schemas:

```bash
$govuk-docker startup
Unknown stack: app.

Available stacks:

lite


$govuk-docker startup lite

Unknown stack: app-lite.

Available stacks:

lite
```

Have tried passing `--stack=lite` which used to work but has now been removed from govuk-docker.

**Comment by thomasleese** [comment]
This is intentional, albeit slightly confusing. If the service doesn't have an `app-` prefixed stack, then it can't be run using the `startup` command. Instead you would use the normal `run` command.

This is to make a distinction between apps where "starting up" is meaningful (such as a web application) and apps where this makes less sense (such as the content schemas).

The error message could definitely be improved though...

**Comment by ChrisBAshton** [comment]
Cool, thanks for explaining 👍 perhaps we can check if an app has no `app-` prefixed stacks, and throw a more helpful error message if the dev tries running `startup`.
