### ISSUE TITLE
Initial installation assumes rbenv but not setup

### ISSUE THREAD

**Issue by kevindew** [alphagov/govuk-docker#589]
We have an issue that the [installation instructions](https://github.com/alphagov/govuk-docker#installation) expects a `bundle install` step before `bin/setup`, on a new machine this will use system Ruby and on GDS current dev machines this won't work due to the bundle lockfile version. Example error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe’: Could not find ‘bundler’ (2.1.4) required by your /Users/matt.hill/govuk/govuk-docker/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path’
	from /usr/bin/bundle:23:in `<main>'
```

[We install `rbenv` as part of `bin/setup`](https://github.com/alphagov/govuk-docker/blob/66422629be24a2e10ebd289cd50844729461c70b/Brewfile#L2) however rbenv is not configured nor is a Ruby version installed so this doesn't really help anyone progress with a Ruby installation.

Some options I could see to proceed with this:

1) Drop `bundle install` from initial install step, you don't actually need it until you run `govuk-doctor` or the tests. This seems a bit funky as you'll have parts of the repo that might not work and need extra instructions to set them up
2) Remove `rbenv` from Brewfile and suggest a dev sets that up first with a link to rbenv instructions - this is probably the lowest effort approach.
3) Set-up rbenv as part of `bin/setup` - this is most consistent with current approach - this would mean us having to modify a ~/.zshrc file run source on it and then `rbenv install` and `bundle install`. This one is a bit of a pain for being invasive (changing the zshrc file feels like a confirm action) or assuming someone uses zsh

I'm somewhat of the view that 2 is the best option where 3 just seems like more things for us to maintain and to break, but I feel like I'm a little out of step with how far we want `bin/setup` to go (it already seems to go pretty far)

**Comment by AshGDS** [comment]
Hi @kevindew 

Thanks for this.

I'm a new starter and had the same issue as the previous developer did who asked for help on Slack. I don't have any experience with Ruby so I can't comment on your suggested fix. However, I thought it would be worth documenting steps on how I fixed the issue, as I suspect more new starters might have the issue and we could refer them to this. To fix it for now I: 

1. Ran `brew install rbenv ruby-build` to install rbenv
2. Added the rbenv Ruby bin and init command to my `~/.zshrc` file as so:
```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)”
```
3. Ran `source ~/.zshrc` to apply the above terminal config
4. Ran `rbenv install` in the govuk-docker directory
5. Ran `gem install bundler` as it seemed to be using bundler v1 which was too old. (This step may be optional, as I did this while I was accidentally still using the default Mac ruby, instead of rbenv's ruby. Which was fixed by incorporating step 2.)
6. Running `bundle install` should work now. If not try running `bin/setup` first.

Thanks :+1:
